default: &default
  adapter: mysql2
  pool: 5
  reconnect: true
  username: root
  password: root123

development:
  <<: *default
  database: base_demo

prepare:
  <<: *default
  database: base_demo

production:
  <<: *default
  database: base_demo    

