default: &default
  adapter: mysql2
  pool: 5
  reconnect: true
  username: root
  password: jamst@123

development:
  <<: *default
  database: product-flow

prepare:
  <<: *default
  database: product-flow

production:
  <<: *default
  database: product-flow    

