# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

redis: &redis
  redis_host: 127.0.0.1
  redis_port: 6379
  redis_db: 1
  redis_node_db: 3
  redis_namespace: fulmo
  redis_pwd: null

default: &default

development:
  <<: *redis
  <<: *default
  secret_key_base: d016ae29eadc1273641eecb6d3658dedf58dc2640e459515b3dd0476ab591349b28245e4f87bf52f31cd447b64bcb549263dcac62e265091b61d7c1d5e60c7ca

test:
  secret_key_base: 774e469c0453730c332960283477296085251c92408ae81976ef1b6b74fb410a6cf336179efe71e39f01f2d67e8823a0533a5bc61bf9ce06c7fc9b80627c4b39

# Do not keep production secrets in the repository,
# instead read values from the environment.
prepare:
  <<: *redis
  <<: *default
  secret_key_base: d016ae29eadc1273641eecb6d3658dedf58dc2640e459515b3dd0476ab591349b28245e4f87bf52f31cd447b64bcb549263dcac62e265091b61d7c1d5e60c7ca

production:
  <<: *redis
  <<: *default
  secret_key_base: d016ae29eadc1273641eecb6d3658dedf58dc2640e459515b3dd0476ab591349b28245e4f87bf52f31cd447b64bcb549263dcac62e265091b61d7c1d5e60c7ca
